services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\CrudBundle\:
        resource: '../../*'
        exclude: '../../{Normalizer,Definition}'

    whatwedo\CrudBundle\Controller\:
        resource: '../../Controller'
        tags:
            - controller.service_arguments

    whatwedo\CrudBundle\Block\Block:
        tags:
            - crud.block

    whatwedo\CrudBundle\View\DefinitionView:
        shared: false
        arguments:
            $accessMap: '@security.access_map'

    whatwedo\CrudBundle\View\DefinitionViewInterface: '@whatwedo\CrudBundle\View\DefinitionView'

    whatwedo\CrudBundle\Routing\CrudLoader:
        tags:
            - { name: routing.loader }

    whatwedo\CrudBundle\EventListener\CrudDefinitionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    whatwedo\CrudBundle\Extension\BreadcrumbsExtension:
        arguments:
            - '@white_october_breadcrumbs'
            - '%whatwedo_crud.config.breadcrumbs.home.text%'
            - '%whatwedo_crud.config.breadcrumbs.home.route%'
