araise_crud:
    resource: .
    type: araise_crud

araise_crud_crud_select_ajax:
    path: /araise/crud/select/ajax
    defaults: { _controller: araise\CrudBundle\Controller\RelationController::ajaxAction }

araise_crud_dashboard:
    path: /dashboard
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: '@araiseCrud/dashboard.html.twig'

araise_crud_search:
    path: /araise_crud_search
    controller: araise\CrudBundle\Controller\SearchController::searchAction
