whatwedo_crud:
    resource: .
    type: whatwedo_crud

whatwedo_crud_crud_select_ajax:
    path: /whatwedo/crud/select/ajax
    defaults: { _controller: whatwedo\CrudBundle\Controller\RelationController::ajaxAction }

whatwedo_crud_dashboard:
    path: /dashboard
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: '@whatwedoCrud/dashboard.html.twig'

whatwedo_crud_search:
    path: /whatwedo_crud_search
    controller: whatwedo\CrudBundle\Controller\SearchController::searchAction
