parameters:
    araise_crud.menu_builder.class: 'araise\CrudBundle\Menu\MenuBuilder'
    env(HTML5_VALIDATION): "false"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $html5Validation: '%env(bool:HTML5_VALIDATION)%'

    araise\CrudBundle\:
        resource: '../../*'
        exclude:
            - '../../Normalizer/'
            - '../../Test/'


    araise\CrudBundle\Builder\DefinitionBuilder:
        shared: false

    araise\CrudBundle\View\DefinitionView:
        shared: false

    araise\CrudBundle\Block\:
        resource: '*'
        shared: false

    araise\CrudBundle\Content\:
        resource: '*'
        shared: false

    araise\CrudBundle\Routing\CrudLoader:
        tags:
            - { name: routing.loader }

    araise\CrudBundle\EventListener\CrudDefinitionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    araise\CrudBundle\Extension\BreadcrumbsExtension:
        arguments:
            - '@white_october_breadcrumbs'
            - '%araise_crud.config.breadcrumbs.home.text%'
            - '%araise_crud.config.breadcrumbs.home.route%'

    araise\CrudBundle\Manager\BlockManager:
        arguments:
            - !tagged_iterator 'araise_crud.block'

    araise\CrudBundle\Manager\ContentManager:
        arguments:
            - !tagged_iterator 'araise_crud.content'

    araise\CrudBundle\Manager\DefinitionManager:
        arguments:
            - !tagged_iterator 'araise_crud.definition'


    araise\CrudBundle\Maker\MakeDefinition:
        arguments:
            - '@maker.doctrine_helper'
            - '@maker.renderer.form_type_renderer'
            - '%kernel.project_dir%'
            - '@araise\CoreBundle\Manager\FormatterManager'
        tags:
            - { name: maker.command }

    araise_crud.menu_builder:
        class: '%araise_crud.menu_builder.class%'
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSubMenu, alias: sub }

    araise\CrudBundle\Twig\CrudTurboExtension:
        arguments: [ "%araise_crud.enable_turbo%" ]
