name: PHP Symfony CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main, develop ]

env:
    DATABASE_URL: mysql://root:root@127.0.0.1:3306/crud_bundle

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [8.1, 8.2, 8.3]
                symfony: [6.4.*, 7.0.*, 7.1.*]
                exclude:
                    - php: 8.1
                      symfony: 7.1.*
                    - php: 8.1
                      symfony: 7.0.*

        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd "mysqladmin ping --silent"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 3

        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: flex
            - name: Download dependencies
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}
              uses: ramsey/composer-install@v2
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install and build assets
              run: |
                  cd tests/App
                  yarn install
                  yarn dev
            - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
              run: vendor/bin/simple-phpunit
            - name: Run ECS
              run: vendor/bin/ecs
            - name: Run PHPStan
              run: vendor/bin/phpstan analyse src tests
